# Generated by Django 2.0 on 2020-07-06 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20200706_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usermasuk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poto_profil', models.ImageField(default='', upload_to='profil/')),
                ('email', models.EmailField(max_length=254)),
                ('jenis_kelamin', models.CharField(max_length=10)),
                ('user_masuk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='detail',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='post',
            name='nama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Usermasuk'),
        ),
    ]
