# Generated by Django 2.0 on 2020-07-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200706_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='gambar',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='usermasuk',
            name='poto_profil',
            field=models.ImageField(blank=True, default='', null=True, upload_to='profil/'),
        ),
    ]
