# Generated by Django 2.0 on 2020-07-06 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200706_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermasuk',
            name='nama_user_masuk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semua_user_masuk', to=settings.AUTH_USER_MODEL),
        ),
    ]
