# Generated by Django 2.0 on 2020-07-06 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200706_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='nama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semua_postingan', to='blog.Usermasuk'),
        ),
    ]
